name: Rust
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
permissions:
  contents: write # Required for creating releases
  actions: read
  checks: read
jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --check

      - name: Run clippy
        env:
          RUSTFLAGS: "-Dwarnings"
        run: cargo clippy --all-targets --all-features

  test:
    name: Test
    runs-on: ubuntu-24.04
    needs: quality
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          profile: minimal
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-
      - name: Run tests
        run: RUSTFLAGS=-Awarnings cargo test --verbose

  build:
    name: Build binaries
    needs: [quality, test]
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            name: DPXRust-linux-gnu-x86_64
          - target: x86_64-pc-windows-msvc
            os: windows-2025
            name: DPXRust-windows-x86_64.exe
          - target: aarch64-apple-darwin
            os: macos-15
            name: DPXRust-aarch64-apple-darwin
          - target: x86_64-apple-darwin
            os: macos-15
            name: DPXRust-x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          target: ${{ matrix.target }}
          override: true
          components: llvm-tools-preview

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Copy  binary (Unix)
        if: matrix.os != 'windows-2025'
        run: |
          cp target/${{ matrix.target }}/release/DPXRust ${{ matrix.name }}
      - name: Copy binary (Windows)
        if: matrix.os == 'windows-2025'
        run: |
          copy target\${{ matrix.target }}\release\DPXRust.exe ${{ matrix.name }}
        shell: cmd

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Display structure of downloaded files
        run: ls -la ./artifacts/
      - name: Prepare release files
        run: |
          mkdir -p ./release
          find ./artifacts -name "DPXRust-*" -type f -exec cp {} ./release/ \;
          ls -la ./release/
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
